# -*- coding: utf-8 -*-
{
    "name": "Api",
    "summary": "API Module",
    "author": "Smarten Technologies",
    "website": "https://www.smarten.com.np",
    "category": "Tools",
    "version": "0.1",
    "depends": [
        "base",
        "stock",
        "route_management",
        "product",
        "hr_attendance",
        "sale_management",
        "sale_commission",
        "crm",
        "mail",
        "custom_payment_ledger",
        "website",
        "expo-notifications"
    ],
    "data": [
        "data/sequence.xml",
        "security/ir.model.access.csv",
        "views/banner_image_view.xml",
        "views/crm_view.xml",
        "views/distribute_order.xml",
        "views/ir_cron.xml",
        "views/partner_location.xml",
        "views/pricelist_view.xml",
        "views/product_category_view.xml",
        "views/product_form_view.xml",
        "views/res_partner_category.xml",
        "views/res_partner.xml",
        "views/res_users_views.xml",
        "views/route_schedule_view.xml",
        "views/sale_commission_target.xml",
        "views/sale_order.xml",
        "reports/customer_due_view.xml",
        "reports/partner_ledger_view.xml",
        "views/sale_person_report_views.xml",
        "views/attendance_view.xml",
        # "views/distributor_report.xml",
        "wizard/distributor_achievement_wizard.xml",
        "views/distributor_commission_plan.xml",
        "views/achievement_report.xml"
        # "views/res_config_settings_view.xml"
    ],
}
